# -*- coding: utf-8 -*-
"""ai_hw01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159PywRBypvYWgBEmfTO424Chz3-nSTlS
"""

import pandas as pd
import os

Dataset_File = "WeatherData.csv"
if not os.path.isfile(Dataset_File):
  os.system("wget https://raw.githubusercontent.com/cnchi/datasets/master/" + Dataset_File)

dfCSV = pd.read_csv("WeatherData.csv")
print(dfCSV)

ary = dfCSV.to_numpy()
print(ary)

dfCSV.describe(include="all")

average_temperature = dfCSV['氣溫(℃)'].mean()
max_humidity = dfCSV['相對溼度(%)'].max()
min_pressure = dfCSV['當日氣壓(hPa)'].min()
total_rainfall = dfCSV['降水量(mm)'].sum()
print("平均溫度: " + str(average_temperature) + " ℃")
print("最高溼度: " + str(max_humidity) + "%")
print("最低氣壓: " + str(min_pressure) + " hPa")
print("總雨量: " + str(total_rainfall) + " mm")

import matplotlib.pyplot as plt

# 先檢查 Colab 目前 Python 版本（至小數點下兩位），得知將來字形檔安裝路徑
!python --version

# 下載台北思源黑體，並命名taipei_sans_tc_beta.ttf
!wget -O taipei_sans_tc_beta.ttf https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download

# 移至指定路徑（若 Python 版本並非 3.10，則需配合更改）
!mv taipei_sans_tc_beta.ttf /usr/local/lib/python3.10/dist-packages/matplotlib/mpl-data/fonts/ttf

# 自定義字體變數（若 Python 版本並非 3.10，則需配合更改）
from matplotlib.font_manager import FontProperties
myfont = FontProperties(fname=r'/usr/local/lib/python3.10/dist-packages/matplotlib/mpl-data/fonts/ttf/taipei_sans_tc_beta.ttf')

# 後續在相關函式中，使用 myfont 做為指定字形即可。
# 如：plt.xlabel("時間", fontproperties=myfont)
# 如：plt.legend(loc='best', prop=myfont)

dates = dfCSV['觀測日期(day)']
temperature = dfCSV['氣溫(℃)']

# Plotting the line chart
plt.figure(figsize=(10,6))
#plt.plot(dates, rainfall, marker='o', linestyle='-', color='b')
plt.plot(dates, temperature, color = 'b', label="氣溫")

# Adding labels and title
plt.xlabel("日期", fontproperties=myfont)
plt.ylabel('氣溫(℃)', fontproperties=myfont)
plt.title('2023年6月溫度折線圖', fontproperties=myfont)

# Display the plot
plt.xticks(dates)  # Ensure all dates are visible on the x-axis
plt.show()
